// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msodyilvoumxyieznofi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zb2R5aWx2b3VteHlpZXpub2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTMyOTIsImV4cCI6MjA3Mjk4OTI5Mn0.DafUk_CWm_VSOzLt6gIdBGWvxzsA6YjPggTT7K2yWlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});